# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ConsolidateNetworks
                                 A QGIS plugin
 Consolidate Networks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-25
        copyright            : (C) 2022 by Simon Ducournau / Circet
        email                : simon.ducournau@circet.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ConsolidateNetworksManager class from file consolidate_networks.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .consolidate_networks import ConsolidateNetworksManager
    return ConsolidateNetworksManager(iface)
